ARG GO_IMAGE=golang:1.22

FROM ${GO_IMAGE}

WORKDIR /go/src/github.com/digitalocean/flipop

ENV GOPATH="/go"
COPY . /go/src/github.com/digitalocean/flipop

RUN go mod download

# k8s.io/code-generator
# Note: This is kept at a rather old version for now to keep diffs small.
RUN mkdir -p /go/src/k8s.io && \
  cd /go/src/k8s.io && \
  git clone --depth 1 --branch v0.20.5 https://github.com/kubernetes/code-generator.git
