apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodednsrecordsets.flipop.digitalocean.com
spec:
  group: flipop.digitalocean.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                addressType:
                  type: string
                match:
                  type: object
                  properties:
                    nodeLabel:
                      type: string
                    podLabel:
                      type: string
                    podNamespace:
                      type: string
                    tolerations:
                      type: array
                      items:
                        type: object
                        properties:
                          effect:
                            type: string
                          key: 
                            type: string
                          operator:
                            type: string
                          value: 
                            type: string
                dnsRecordSet:
                  type: object
                  required:
                  - provider
                  properties:
                    provider:
                      type: string
                    zone:
                      type: string
                    recordName:
                      type: string
                    ttl:
                      type: integer
            status:
              type: object
              properties:
                error:
                  type: string
  scope: Namespaced
  names:
    kind: NodeDNSRecordSet
    listKind: NodeDNSRecordSetList
    plural: nodednsrecordsets
    singular: nodednsrecordset
    shortNames: [nodedns]